name: Lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: clippy
        run: cargo clippy --verbose
      - name: fmt
        run: cargo fmt --verbose -- --check
